"""rename department

Revision ID: 768737f19dca
Revises: c92db90368cf
Create Date: 2025-09-26 16:59:35.698798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768737f19dca'
down_revision = 'c92db90368cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
